name: tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: ^3.10
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run tests and lint
        run: |
            make pyt
            make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
        continue-on-error: true
